title: Pranav's Blog
author: Pranav Vempati
email: pranav.k.vempati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 My projects and blog posts relevant to them. Occasional math/physics posts. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  pranav-vempati # DO NOT include the @ character, or else the build will fail!
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
